### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/smartcitizen-onboarding-app-iscape#6]
- [x] Green buttons hover color #AAD77F

- [x] BACK button background color (INACTIVE): #008ECF
- [x] BACK button background color (HOVER): #004F74

- [x] Progress bar text font: KANIT 700 / 20px
- [x] Progress bar text color (INACTIVE): #008ECF
- [x] Progress bar text color (HOVER): #004F74

- [x] Change red to #EF5050

- [x] Placeholders text and icons color (INACTIVE): #74D3FF
- [x] Placeholders background box color: #008ECF

- [ ] Considerably reduce the padding between H1 and the paragraphs
_This way, we will also gain some space for the content to not go out of the screens_

- [x] Reduce the size of the SCK layout on big screens (on light handshake method)

- [ ] Write copies for the "INFO" buttons on the screen to select the handshake method
